### ISSUE TITLE
[v1.3.1] 无法发送消息

### ISSUE THREAD

**Issue by Kiritow** [mamoe/mirai-api-http#22]
Win10 18363 (1909)
Oracle Java 1.8.0_221 64位
mirai-api-http版本：v1.3.1
mirai-console版本：0.3.7
mirai-core-jvm版本：0.30.0
mirai-core-qqandroid-jvm版本：0.30.0
登录QQ正常，AuthKey + Verify正常，调用sendFriendMessage和sendGroupMessage接口时报错：

```
[0m 00:59:05 [38;5;196m[ERROR][39;49m [MiraiAPIHTTP] java.lang.NoSuchMethodError: net.mamoe.mirai.message.data.PlainText.constructor-impl(Ljava/lang/String;)Ljava/lang/String;
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:156)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:130)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$1$1.invokeSuspend(BaseRoute.kt:326)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$1$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.routing.Routing.executeResult(Routing.kt:147)
        at io.ktor.routing.Routing.interceptor(Routing.kt:34)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:120)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:167)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

回退mirai-core-jvm, mirai-core-qqandroid-jvm到0.29.1后（通过修改文件后缀名跳过了强制更新），登录QQ（login）指令时报错，无法收到消息，调HTTP接口发送消息时始终返回错误：`5 发送消息目标不存在(指定对象不存在)`
```
[0m 01:13:33 [INFO] [Mirai 0.3.7 Pkmon] java.lang.NoSuchMethodError: net.mamoe.mirai.Bot.login(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
        at net.mamoe.mirai.console.command.DefaultCommands$invoke$2$1.invokeSuspend(DefaultCommands.kt:139)
        at net.mamoe.mirai.console.command.DefaultCommands$invoke$2$1.invoke(DefaultCommands.kt)
        at net.mamoe.mirai.console.command.AnonymousCommand.onCommand(Command.kt:124)
        at net.mamoe.mirai.console.command.CommandManager.processCommandImpl(CommandManager.kt:154)
        at net.mamoe.mirai.console.command.CommandManager$processCommand$2.invokeSuspend(CommandManager.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by ryoii** [comment]
版本升级导致，等待发布新版本
