### ISSUE TITLE
添加插件后报错

### ISSUE THREAD

**Issue by leeyiding** [mamoe/mirai-api-http#36]
没添加插件前运行正常，添加后运行程序，报错如下

You are running Mirai-Console-Wrapper under /root/qqbot
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version .. 
Fetching Newest Console Version of Pure
Local Core Version: 0.33.0 | Newest Core Version: 0.33.0
Local Console-Pure Version: 0.4.3 | Newest Console-Pure Version: 0.4.3
Version check complete, starting Mirai
shadow-Protocol:/root/qqbot/content/mirai-core-qqandroid-jvm-0.33.0.jar
Console        :/root/qqbot/content/mirai-console-0.4.3.jar
Root           :/root/qqbot/
 00:32:35 [INFO] [Mirai 0.4.3 Pkmon] Mirai-console now running under /root/qqbot
 00:32:35 [INFO] [Mirai 0.4.3 Pkmon] Get news in github: https://github.com/mamoe/mirai
 00:32:35 [INFO] [Mirai 0.4.3 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
 00:32:35 [INFO] [Mirai 0.4.3 Pkmon] Powered by Mamoe Technologies and contributors
 00:32:35 [INFO] [Plugin Manager] 开始加载/root/qqbot/plugins/下的插件
 00:32:35 [INFO] [Plugin Manager] loading plugin MiraiAPIHTTP
Exception in thread "main" java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at net.mamoe.mirai.console.wrapper.WrapperMain.start(WrapperMain.kt:150)
at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative(WrapperMain.kt:133)
at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:89)
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'void net.mamoe.mirai.console.plugins.PluginBase.<init>(kotlin.coroutines.CoroutineContext, int, kotlin.jvm.internal.DefaultConstructorMarker)' the class loader net.mamoe.mirai.console.plugins.PluginClassLoader @7c1e2a2d of the current class, net/mamoe/mirai/api/http/HttpApiPluginBase, and the class loader net.mamoe.mirai.console.wrapper.MiraiClassLoader @23202fce for the method's defining class, net/mamoe/mirai/console/plugins/PluginBase, have different Class objects for the type kotlin/jvm/internal/DefaultConstructorMarker used in the signature (net.mamoe.mirai.api.http.HttpApiPluginBase is in unnamed module of loader net.mamoe.mirai.console.plugins.PluginClassLoader @7c1e2a2d, parent loader net.mamoe.mirai.console.plugins.PluginsClassLoader @2f16c6b3; net.mamoe.mirai.console.plugins.PluginBase is in unnamed module of loader net.mamoe.mirai.console.wrapper.MiraiClassLoader @23202fce, parent loader 'bootstrap')
at net.mamoe.mirai.api.http.HttpApiPluginBase.<init>(HttpApiPluginBase.kt:24)
at net.mamoe.mirai.api.http.HttpApiPluginBase.<clinit>(HttpApiPluginBase.kt:24)
at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
at java.base/java.lang.reflect.Field.get(Field.java:418)
at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:114)
at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62)
at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt)
at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:239)
at net.mamoe.mirai.console.plugins.PluginManager$loadPlugins$4.invoke(PluginManager.kt:181)
at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins(PluginManager.kt:206)
at net.mamoe.mirai.console.MiraiConsole.start(MiraiConsole.kt:85)
at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion.load(MiraiConsolePureLoader.kt:22)
at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.load(MiraiConsolePureLoader.kt)
... 7 more

**Comment by ryoii** [comment]
是否是添加**其他**插件后报错

**Comment by leeyiding** [comment]
> 是否是添加**其他**插件后报错

第一次安装，只添加了这一个插件

**Comment by ryoii** [comment]
请提供下`mirai-api-http`的版本号

**Comment by leeyiding** [comment]
> 请提供下`mirai-api-http`的版本号

v1.4.1和v1.5.0都尝试过

**Comment by ryoii** [comment]
测试为`console`更新产生的问题

**Comment by ryoii** [comment]
v1.5.1修复该问题

**Comment by Tarocch1** [comment]
新版本的 console 似乎也不可以。

```
 23:34:18 [INFO] [Plugin Manager] loading plugin MiraiAPIHTTP
 23:34:18 [INFO] [Plugin Manager] successfully loaded plugin MiraiAPIHTTP version v1.5.0 by ryoii
 23:34:18 [INFO] [Plugin Manager] Mirai HTTP API Server Plugin
 23:34:18 [INFO] [MiraiAPIHTTP] Loading Mirai HTTP API plugin
 23:34:18 [INFO] [MiraiAPIHTTP] Trying to Start Mirai HTTP Server in 0.0.0.0:8080
 23:34:18 [INFO] [MiraiAPIHTTP] Starting Mirai HTTP Server in 0.0.0.0:8080
Mirai HTTP API 23:34:18 : Http api server is running with authKey: 1234567890
 23:34:18 [INFO] [Plugin Manager] 加载了1个插件
 23:34:18 [INFO] [Mirai 0.4.6 Pkmon] Mirai-console 启动完成
 23:34:18 [INFO] [Mirai 0.4.6 Pkmon] "/login qqnumber qqpassword " to login a bot
 23:34:18 [INFO] [Mirai 0.4.6 Pkmon] "/login qq号 qq密码 " 来登录一个BOT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
 23:34:18 [INFO] [MiraiAPIHTTP] kotlin.UninitializedPropertyAccessException: lateinit property server has not been initialized
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer.stop(MiraiHttpAPIServer.kt:69)
        at net.mamoe.mirai.api.http.HttpApiPluginBase.onDisable(HttpApiPluginBase.kt:50)
        at net.mamoe.mirai.console.plugins.PluginBase.disable$mirai_console(PluginBase.kt:127)
        at net.mamoe.mirai.console.plugins.PluginManager.disablePlugins(PluginManager.kt:258)
        at net.mamoe.mirai.console.plugins.PluginManager.disablePlugins$default(PluginManager.kt:255)
        at net.mamoe.mirai.console.MiraiConsole.stop(MiraiConsole.kt:98)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion$load$1.invoke(MiraiConsolePureLoader.kt:28)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion$load$1.invoke(MiraiConsolePureLoader.kt:16)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

java.lang.NoClassDefFoundError: io.ktor.config.MapApplicationConfig
        at io.ktor.server.engine.ApplicationEngineEnvironmentBuilder.<init>(ApplicationEngineEnvironment.kt:75)
        at io.ktor.server.engine.ApplicationEngineEnvironmentKt.applicationEngineEnvironment(ApplicationEngineEnvironment.kt:44)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2.invokeSuspend(MiraiHttpAPIServer.kt:54)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by ryoii** [comment]
v1.5.1修复该问题
