### ISSUE TITLE
fetchMessage 时报错

### ISSUE THREAD

**Issue by SettingDust** [mamoe/mirai-api-http#39]
`Unknown error @ fetchMessage: Request failed with status code 500`
```
09:46:27[ERROR][MiraiAPIHTTP] java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.api.http.util.FaceMap
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toDTO(MessageDTO.kt:152)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toDTO(MessageDTO.kt:215)
        at net.mamoe.mirai.api.http.data.common.BotEventDTOKt.toDTO(BotEventDTO.kt:22)
        at net.mamoe.mirai.api.http.queue.MessageQueue.fetch(MessageQueue.kt:27)

        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$1.invokeSuspend(MessageRouteModule.kt:38)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$1.invoke(MessageRouteModule.kt)
        at net.mamoe.mirai.api.http.route.BaseRouteKt$miraiGet$1$$special$$inlined$intercept$1.invokeSuspend(BaseRoute.kt:323)
        at net.mamoe.mirai.api.http.route.BaseRouteKt$miraiGet$1$$special$$inlined$intercept$1.invoke(BaseRoute.kt)
```

**Comment by ryoii** [comment]
暂时 face 和 poke 消息会报错
