### ISSUE TITLE
修改群成员信息返回值不正常;kick群成员报错

### ISSUE THREAD

**Issue by zhzRedstone** [mamoe/mirai-api-http#48]
```
POST /memberInfo HTTP/1.1
Content-Length: 161
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:5710
{
  	"sessionKey": "I8OXUhZl",
	"target": 1048307612,
	"memberId": 1786630005
    "info": {
        "name": "凋零",
        "specialTitle": "星号酱"
    }
}

HTTP/1.1 200 OK
Date: Thu, 09 Apr 2020 14:27:38 GMT
Server: Application/debug ktor/debug
Content-Length: 35
Content-Type: application/json; charset=UTF-8
Connection: keep-alive
{"code":10,"msg":"无操作权限"}

```
此时群成员已改名
```
POST /kick HTTP/1.1
Content-Length: 105
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:5710
{
  	"sessionKey": "I8OXUhZl",
	"target": 1048307612,
	"memberId": 1786630005
    "msg": "踢人测试"
}

HTTP/1.1 500 Internal Server Error
Date: Thu, 09 Apr 2020 14:32:37 GMT
Server: Application/debug ktor/debug
Content-Length: 25
Content-Type: text/plain; charset=UTF-8
Connection: keep-alive
kick failed: 踢人测试
```
log:
```
 22:36:18 [INFO] [ConsoleAddition] [NETWORK] Send done: OidbSvc.0x8a0_0
 22:36:18 [INFO] [ConsoleAddition] [NETWORK] Event: TroopManagement.Kick.Response(false)
 22:36:18 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: kick failed: 踢人测试
        at net.mamoe.mirai.qqandroid.contact.MemberImpl.kick(MemberImpl.kt:184)
        at net.mamoe.mirai.qqandroid.contact.MemberImpl$kick$1.invokeSuspend(MemberImpl.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
此时群成员已被踢出

**Comment by ryoii** [comment]
问题没有复现，请确保bot拥有管理员权限。

关于第一个问题，修改群头衔需要群主权限
