### ISSUE TITLE
0.27.0发送图片不稳定

### ISSUE THREAD

**Issue by dev-techmoe** [mamoe/mirai-api-http#7]
偶尔尝试发图的时候mirai-console会报错
```
java.lang.IllegalStateException: send message failed: MessageSvc.PbSendMsg.Response.Failed(resultType=34, errorCode=0, errorMessage=)
        at net.mamoe.mirai.qqandroid.GroupImpl.sendMessage(ContactImpl.kt:603)
        at net.mamoe.mirai.qqandroid.GroupImpl$sendMessage$1.invokeSuspend(ContactImpl.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
我也在尝试去寻找一个比较稳定的复现方式。稍微测试了一下，当单条消息发送超过五张图片的时候会发送失败，但是有的时候发两张不同的图也会失败。  
按照我对文档的理解，我发图的过程是，先调用`/uploadImage`接口去上传图片，然后把该接口返回值里添加一条`{"type":  "Image"}`直接作为messageChain的元素进行发送。
测试用的大致的封包结构：
```
{
    "target":111111,
    "messageChain":[
        {
            "imageId":"{11}.jpg",
            "url":"http://gchat.qpic.cn/gchatpic_new/01/0",
            "type":"Image"
        },
        {
            "imageId":"{11}.jpg",
            "url":"http://gchat.qpic.cn/gchatpic_new/01/0",
            "type":"Image"
        },
        {
            "type":"Plain",
            "text":"abfbfdbc"
        },
        {
            "imageId":"{11}.jpg",
            "url":"http://gchat.qpic.cn/gchatpic_new/01/0",
            "type":"Image"
        },
    ],
    "sessionKey":"absdcsd"
}
```

**Comment by ryoii** [comment]
这是因为当前Mirai对于消息包没有进行分包，导致的问题是长消息发送失败。
同类问题有：
+ 多图片消息
+ 长文本消息
+ 带图片Quote消息

该问题在若干个版本迭代后解决，建议避免发送过长的消息

**Comment by Him188** [comment]
[mirai#90](https://github.com/mamoe/mirai/issues/90)

**Comment by dev-techmoe** [comment]
更新至新版本后问题解决，辛苦了👍
