### ISSUE TITLE
引用带图消息时抛出异常

### ISSUE THREAD

**Issue by Nutr1t07** [mamoe/mirai-api-http#75]
# 描述

机器人回复好友私聊时quote的消息内容中若含有图片会抛出`IllegalStateException`异常。quote不带图消息正常；回复群消息正常。

# 日志
 ```
22:09:24 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: send message failed
        at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:41)
        at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
# 环境

Core 0.39.5
Console-Pure 0.4.11
mirai-core-qqandroid-jvm 0.39.5
MiraiAPIHTTP 1.6.5

# 其他

我不能确定这是否为上游的问题，相关代码在此处：
https://github.com/mamoe/mirai/blob/1a557984f4d7b1d5ea970bc5574c728ad72e1dee/mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/util.kt#L39-L51

**Comment by ryoii** [comment]
已知问题，带图quote属于长消息。好友消息和临时会话暂时不支持长消息。
