### ISSUE TITLE
接收到带有引用消息的时候会报错

### ISSUE THREAD

**Issue by frencis107** [mamoe/mirai-api-http#79]
运行环境：`Windows 10`
mirai-console  : `0.5.1`
mirai-console-wrapper : `1.1.0`
mirai-api-http : `v1.6.5`

我使用的是 `python-mirai` ，在收到带有引用回复消息会报以下错误
`[2020-05-08 04:22:04][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.`

![Snipaste_2020-05-08_12-22-13.png](https://i.loli.net/2020/05/08/C3FldErtxhoge49.png)

查看 `mirai-console` 日志，当接收到群组/私聊带有引用回复的消息、XML卡片消息`（例如位置信息）`时，控制台都会出现以下错误

错误信息：
```
 12:22:03 [INFO] [BOT 2236056826] [FTest(232466435)] 107(1071788372) -> [mirai:source:4164,-1034406751][mirai:at:1071788372] [mirai:quote:4163,-1393828625]123
 12:22:04 [ERROR] [MiraiAPIHTTP] java.lang.NoClassDefFoundError: net/mamoe/mirai/message/data/XmlMessage
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toDTO(MessageDTO.kt:161)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toDTO(MessageDTO.kt:219)
        at net.mamoe.mirai.api.http.data.common.BotEventDTOKt.toDTO(BotEventDTO.kt:22)
        at net.mamoe.mirai.api.http.queue.MessageQueue.fetch(MessageQueue.kt:27)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$2.invokeSuspend(MessageRouteModule.kt:55)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$2.invoke(MessageRouteModule.kt)
        at net.mamoe.mirai.api.http.route.BaseRouteKt$miraiGet$1$$special$$inlined$intercept$1.invokeSuspend(BaseRoute.kt:324)
        at net.mamoe.mirai.api.http.route.BaseRouteKt$miraiGet$1$$special$$inlined$intercept$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.routing.Routing.executeResult(Routing.kt:147)
        at io.ktor.routing.Routing.interceptor(Routing.kt:34)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:120)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:167)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by Chenwe-i-lin** [comment]
绝了 mirai core 更新后的问题 呢可以等httpapi更新
