### ISSUE TITLE
NoSuchMethodError: io.ktor.server.cio.backend.ServerIncomingConnection.<init>

### ISSUE THREAD

**Issue by Nutr1t07** [mamoe/mirai-api-http#8]
# 问题描述

将`mirai-api-http-v1.2.2.jar`放入`plugins/`内后访问服务器8080端口后程序抛出异常。

# 重现步骤

1. `java -jar mirai_console.jar`

# 日志
```
nutr1t07@iZ9zacvzwqpz8vZ:~/mirai$ java -jar mirai_console.jar                 
You are running Mirai-Console-Wrapper under /home/nutr1t07/mirai
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version .. 
Fetching Newest Console Version of Pure
Local Core Version: 0.27.0 | Newest Core Version: 0.27.0
Local Console-Pure Version: 0.3.4 | Newest Console-Pure Version: 0.3.4
Version check complete, starting Mirai
Core    :/home/nutr1t07/mirai/content/mirai-core-jvm-0.27.0.jar
Protocol:/home/nutr1t07/mirai/content/mirai-core-qqandroid-jvm-0.27.0.jar
Console :/home/nutr1t07/mirai/content/mirai-console-0.3.4.jar
Root    :/home/nutr1t07/mirai/
 10:19:40 [Mirai 0.3.4 Pkmon]: Mirai-console now running under /home/nutr1t07/mirai
 10:19:40 [Mirai 0.3.4 Pkmon]: Get news in github: https://github.com/mamoe/mirai
 10:19:40 [Mirai 0.3.4 Pkmon]: Mirai为开源项目，请自觉遵守开源项目协议
 10:19:40 [Mirai 0.3.4 Pkmon]: Powered by Mamoe Technologies and contributors
 10:19:41 [Plugin Manager]: 开始加载/home/nutr1t07/mirai/plugins/下的插件
 10:19:41 [Plugin Manager]: loading plugin MiraiAPIHTTP
 10:19:41 [Plugin Manager]: successfully loaded plugin MiraiAPIHTTP version v1.2.2 by ryoii
 10:19:41 [Plugin Manager]: Mirai HTTP API Server Plugin
 10:19:41 [MiraiAPIHTTP]: Loading Mirai HTTP API plugin
 10:19:41 [MiraiAPIHTTP]: Trying to Start Mirai HTTP Server in 0.0.0.0:8080
 10:19:41 [MiraiAPIHTTP]: Starting Mirai HTTP Server in 0.0.0.0:8080
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Mirai HTTP API 10:19:41 : Http api server is running with authKey: 1234567890
 10:19:41 [Plugin Manager]: 加载了1个插件
 10:19:41 [Mirai 0.3.4 Pkmon]: Mirai-console 启动完成
 10:19:41 [Mirai 0.3.4 Pkmon]: "/login qqnumber qqpassword " to login a bot
 10:19:41 [Mirai 0.3.4 Pkmon]: "/login qq号 qq密码 " 来登录一个BOT
java.lang.NoSuchMethodError: io.ktor.server.cio.backend.ServerIncomingConnection.<init>(Lio/ktor/utils/io/ByteReadChannel;Lio/ktor/utils/io/ByteWriteChannel;Ljava/net/SocketAddress;Ljava/net/SocketAddress;)V
        at io.ktor.server.cio.backend.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:58)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

# 配置文件

`MiraiAPIHTTP/setting.yml`
```
port: 8080
authKey: 1234567890
cacheSize: 4096
enableWebsocket: false
```

# 环境

- Debian **9.12 stretch**
- **java**
``` 
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-1~deb9u1-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```
- **mirai-console** wrapper-0.1.2
- **mirai-api-http** 1.2.2

**Comment by ryoii** [comment]
暂时使用1.2.1的http插件。
等wrapper更新依赖

**Comment by ryoii** [comment]
wrapper已更新
