### ISSUE TITLE
Uploading image failed

### ISSUE THREAD

**Issue by HoshinoTented** [mamoe/mirai-api-http#85]
I got an error when I uploading an image via `/uploadImage` API:

<details>
<summary>stacktrace</summary>

```plain
02:21:17 [ERROR] [MiraiAPIHTTP] io.ktor.utils.io.charsets.MalformedInputException: Input length = 1
        at io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:323)
        at io.ktor.utils.io.charsets.CharsetJVMKt.decodeImplSlow(CharsetJVM.kt:289)
        at io.ktor.utils.io.charsets.CharsetJVMKt.decodeExactBytes(CharsetJVM.kt:254)
        at io.ktor.utils.io.core.StringsKt.readTextExactBytes(Strings.kt:293)
        at io.ktor.utils.io.core.StringsKt.readTextExactBytes$default(Strings.kt:292)
        at io.ktor.utils.io.core.AbstractInput.readText(AbstractInput.kt:468)
        at io.ktor.utils.io.core.AbstractInput.readText$default(AbstractInput.kt:465)
        at io.ktor.http.cio.CIOMultipartDataBase.partToData(CIOMultipartData.kt:127)
        at io.ktor.http.cio.CIOMultipartDataBase$partToData$1.invokeSuspend(CIOMultipartData.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

</details>

Here is my code, it works with [mirai-rs](https://github.com/HoshinoTented/mirai-rs).

<details>
<summary> upload_image.rs </summary>

```rust
#[tokio::main]
async fn main() {
    const URL: &'static str = "https://avatars3.githubusercontent.com/u/25280943";
    const GROUP: u64 = 972342866;

    let session = connect().await;
    let img = reqwest::get(URL).await.unwrap()
        .bytes().await.unwrap();

    let img = session.upload_image(ImageType::Group, img).await.unwrap();

    println!("Uploaded.");

    session.send_message(MessageChannel::Group(GROUP), &SingleMessage::from(img).into()).await.unwrap();
}
```

</details>

<details>

<summary> image.rs </summary>

```rust
#[serde(rename_all = "camelCase")]
#[derive(Debug, Serialize, Deserialize)]
pub struct Image {
    pub image_id: String,
    pub url: String,
    pub path: String,
}

#[derive(Debug, Clone, Copy)]
pub enum ImageType {
    Friend,
    Group,
    Temp,
}

impl ToString for ImageType {
    fn to_string(&self) -> String {
        match self {
            ImageType::Friend => "friend",
            ImageType::Group => "group",
            ImageType::Temp => "temp",
        }.to_string()
    }
}

impl Session {
    pub async fn upload_image(&self, image_type: ImageType, bytes: Bytes) -> Result<Image> {
        let form = Form::new()
            .text("sessionKey", self.key.clone())
            .text("type", image_type.to_string())
            .part("img", Part::stream(Body::from(bytes)));

        let text = self.client.post(&self.url("/uploadImage"))
            .multipart(form).send().await?
            .text().await?;

        println!("{}", text);

        unimplemented!();         // For testing

        // Ok(resp)
    }
}
```

</details>

I tried in mirai-api-http 1.6.5.

**Comment by ryoii** [comment]
Maybe you should update it to 1.7.0

**Comment by HoshinoTented** [comment]
I got the same error in 1.7.0. 😕

**Comment by ryoii** [comment]
😥

**Comment by HoshinoTented** [comment]
I caught the request and response by Fiddler:
![image](https://user-images.githubusercontent.com/25280943/82152361-2fee9200-9893-11ea-90b7-796d8e8319c1.png)

Is there something wrong?

**Comment by ryoii** [comment]
I'm not sure. I suspect it's a bug for stupid `ktor`.

Are u sure you request `content-type` is `multipart/form-data`?

**Comment by HoshinoTented** [comment]
I am sure, the content-type of the request in the above photo is `multipart/form-data`

**Comment by Executor-Cheng** [comment]
我也遇到相同的问题, 在mirai控制台有以下Stacktrace:
```
[MiraiAPIHTTP] io.ktor.utils.io.charsets.MalformedInputException: Input length = 1
        at io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:323)
        at io.ktor.utils.io.charsets.CharsetJVMKt.decodeImplSlow(CharsetJVM.kt:289)
        at io.ktor.utils.io.charsets.CharsetJVMKt.decodeExactBytes(CharsetJVM.kt:254)
        at io.ktor.utils.io.core.StringsKt.readTextExactBytes(Strings.kt:293)
        at io.ktor.utils.io.core.StringsKt.readTextExactBytes$default(Strings.kt:292)
        at io.ktor.utils.io.core.AbstractInput.readText(AbstractInput.kt:468)
        at io.ktor.utils.io.core.AbstractInput.readText$default(AbstractInput.kt:465)
        at io.ktor.http.cio.CIOMultipartDataBase.partToData(CIOMultipartData.kt:127)
        at io.ktor.http.cio.CIOMultipartDataBase$partToData$1.invokeSuspend(CIOMultipartData.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
请求如下:
![TIM图片20200524155029](https://user-images.githubusercontent.com/27953325/82748652-67e75f00-9dd6-11ea-97b5-b26d203fd6de.png)

**Comment by HoshinoTented** [comment]
I found [this](https://github.com/ktorio/ktor/issues/1766), it may help us.

**Comment by ryoii** [comment]
I work it well

**Comment by ryoii** [comment]
> I work it well

Updata it to `1.8.0` and have a try later.

**Comment by HoshinoTented** [comment]
😢 I got the same error again. How did you do that?

mirai-console-wrapper: 1.2.0
mirai-api-http: 1.7.1

**Comment by ryoii** [comment]
> 😢 I got the same error again. How did you do that?
> 
> mirai-console-wrapper: 1.2.0
> mirai-api-http: 1.7.1

It runs perfectly in `Talend API Tester`, a plugin for chrome

**Comment by HoshinoTented** [comment]
It works! Thanks for your help!
