### ISSUE TITLE
上报功能无法使用

### ISSUE THREAD

**Issue by tobycroft** [mamoe/mirai-api-http#86]
https://github.com/mamoe/mirai-api-http/blob/master/docs/report.md

这个里面的东西只要加入到settings.yml里面去。http插件重启直接炸，删除后恢复

这个是哪里有问题啊

**Comment by tobycroft** [comment]
@copydog

**Comment by tobycroft** [comment]
版本 170



# 可选，心跳服务
heartbeat:
  # 可选，是否启用心跳，默认不启用
  enable: false
  # 可选，心跳启动延迟，默认1000
  delay: 1000
  # 可选，心跳周期，默认15000
  period: 15000
  # 必选，心跳PING的地址列表
  destinations:
    - http://10.0.0.180:90/http/v1/data/index
    
# 可选，上报服务
report:
  # 可选，是否启用上报，默认不启用
  enable: true
  # 可选，上报群消息的配置
  groupMessage:
    # 可选，是否上报，默认不上报
    report: true
  # 可选，上报好友消息的配置
  friendMessage:
    # 可选，是否上报，默认不上报
    report: true
  # 可选，上报事件消息的配置
  eventMessage:
    report: true
  # 必选，上报的地址列表
  destinations:
    - https://postman-echo.com/post
  # 可选，上报时需要带上的请求头
  extraHeaders:
    # 填上你需要的请求头（如授权信息等）
    Authorization: basic xxx

**Comment by tobycroft** [comment]
从1.6.0版本测试到1.7.0，上传均不可使用

**Comment by tobycroft** [comment]
08:27:37 [INFO] [MiraiAPIHTTP] 心跳模块启用状态: false
 08:27:37 [INFO] [MiraiAPIHTTP] 上报模块启用状态: false
 08:27:37 [INFO] [Plugin Manager] 加载了1个插件
 08:27:37 [INFO] [Command] 重新加载完成
java.net.BindException: 地址已在使用
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:78)
        at io.ktor.network.sockets.TcpSocketBuilder.bind(Builders.kt:125)
        at io.ktor.network.sockets.TcpSocketBuilder.bind(Builders.kt:92)
        at io.ktor.network.sockets.TcpSocketBuilder.bind$default(Builders.kt:91)
        at io.ktor.server.cio.backend.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:44)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 08:27:39 [INFO] [NETWORK] unknown group 528 type 0x0000000000000115, data: 08 F0 DF D3 D2 02 10 EA C5 C9 FC 07 1A 29 08 00 10 05 18 BB C4 94 F6 05 20 01 28 FF FF FF FF 0F 32 15 E5 AF B9 E6 96 B9 E6 AD A3 E5 9C A8 E8 BE 93 E5 85 A5 2E 2E 2E
 08:27:39 [INFO] [NETWORK] Send: OnlinePush.RespPush
 08:27:39 [INFO] [NETWORK] unknown group 528 type 0x0000000000000115, data: 08 F0 DF D3 D2 02 10 EA C5 C9 FC 07 1A 14 08 00 10 05 18 BB C4 94 F6 05 20 02 28 FF FF FF FF 0F 32 00
 08:27:39 [INFO] [NETWORK] Send: OnlinePush.RespPush
 08:27:39 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 08:27:39 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 08:27:40 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 08:27:40 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
