### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".                

### ISSUE THREAD

**Issue by StageGuard** [mamoe/mirai-api-http#9]
shows it when starting mirai with mirai-http-api

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".                 SLF4J: Defaulting to no-operation (NOP) logger implementation                    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

and when i post to server using curl

```
curl -X POST -d '{"authKey":"my_key"}' http://192.168.1.2:8080/auth
```

it got error and then api server shutdown automatically.

```
java.lang.NoSuchMethodError: 'void io.ktor.server.cio.backend.ServerIncomingConnection.<init>(io.ktor.utils.io.ByteReadChannel, io.ktor.utils.io.ByteWriteChannel, java.net.SocketAddress, java.net.SocketAddress)'                                        at io.ktor.server.cio.backend.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:58)                                                                 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)                   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)                                                                          at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)                                                                 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)                                                                   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by ryoii** [comment]
What about `SLF4J`  is just a warning. You can ignore it.
And plz update the mirai-console-wrapper to version 0.1.3 to solve your problem.

**Comment by StageGuard** [comment]
@ryoii tkx 4 replying.. and where to upgrade mirai-wrapper? i mean... the release page doesnt contain ver0.1.3.

**Comment by ryoii** [comment]
Now it has.
