### ISSUE TITLE
XML信息出错

### ISSUE THREAD

**Issue by tobycroft** [mamoe/mirai-api-http#90]
![image](https://user-images.githubusercontent.com/24893075/82648827-e3b4a080-9c4a-11ea-8aed-bde53bc45937.png)

 04:39:31 [INFO] [BOT 2140300010] [test(905975198)] ╰⋛⋋ 火线兔 ⋌⋚╯(710209520) -> [mirai:source:12600,1543033646][mirai:service:33,<?xml version='1.0' encoding='UTF-8' standalone='yes'?><msg templateID="123" url="http://www.baidu.com" serviceID="33" action="web" actionData="" brief="【链接】百度一下，你就知道" flag="8"><item layout="2"><picture cover="http://www.baidu.com/img/bd_logo1.png"/><title>百度一下，你就知道</title><summary>百度一下，你就知道新闻hao123地图视频贴吧更多产品关于百度AboutBaidu...</summary></item></msg>]www.baidu.com
 04:39:31 [INFO] [NETWORK] Exception in NetworkHandler
 04:39:31 [INFO] [NETWORK ERROR] java.lang.NoClassDefFoundError: net/mamoe/mirai/message/data/XmlMessage
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toDTO(MessageDTO.kt:161)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toDTO(MessageDTO.kt:220)
        at net.mamoe.mirai.api.http.data.common.BotEventDTOKt.toDTO(BotEventDTO.kt:22)
        at net.mamoe.mirai.api.http.service.report.ReportService$onEnable$1.invokeSuspend(ReportService.kt:60)
        at net.mamoe.mirai.api.http.service.report.ReportService$onEnable$1.invoke(ReportService.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:269)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.internal.InternalEventListenersKt$callAndRemoveIfRequired$3$invokeSuspend$$inlined$forEachNode$lambda$1.invokeSuspend(InternalEventListeners.kt:174)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.message.data.XmlMessage
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 20 more

**Comment by tobycroft** [comment]
发网址的时候出现的，如果信息被解析了，那么就肯定出现这个错误

**Comment by ryoii** [comment]
提供插件版本号

**Comment by tobycroft** [comment]
1.6.5

**Comment by tobycroft** [comment]
@ryoii 因为1.7.0不能用，所以……

**Comment by tobycroft** [comment]
@ryoii #91

**Comment by ryoii** [comment]
更新即可
